Controllers/CoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Arthesanatus.Models;
using Arthesanatus.Models.Context;

namespace Arthesanatus.Controllers
{
    public class CoresController : Controller
    {
        private ArthesContext db = new ArthesContext();

        // GET: Cores
        public ActionResult Index()
        {
            var cORES = db.CORES.Include(c => c.TipoLinha);
            return View(cORES.ToList());
        }

        // GET: Cores/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cor cor = db.CORES.Find(id);
            if (cor == null)
            {
                return HttpNotFound();
            }
            return View(cor);
        }

        // GET: Cores/Create
        public ActionResult Create()
        {
            ViewBag.TipoLinhaID = new SelectList(db.TIPOSLINHAS, "TipoLinhaID", "Nome");
            return View();
        }

        // POST: Cores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CorID,CorCodigo,TipoLinhaID,Nome,QtdFechada,QtdAberta")] Cor cor)
        {
            if (ModelState.IsValid)
            {
                db.CORES.Add(cor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TipoLinhaID = new SelectList(db.TIPOSLINHAS, "TipoLinhaID", "Nome", cor.TipoLinhaID);
            return View(cor);
        }

        // GET: Cores/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cor cor = db.CORES.Find(id);
            if (cor == null)
            {
                return HttpNotFound();
            }
            ViewBag.TipoLinhaID = new SelectList(db.TIPOSLINHAS, "TipoLinhaID", "Nome", cor.TipoLinhaID);
            return View(cor);
        }

        // POST: Cores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CorID,CorCodigo,TipoLinhaID,Nome,QtdFechada,QtdAberta")] Cor cor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TipoLinhaID = new SelectList(db.TIPOSLINHAS, "TipoLinhaID", "Nome", cor.TipoLinhaID);
            return View(cor);
        }

        // GET: Cores/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cor cor = db.CORES.Find(id);
            if (cor == null)
            {
                return HttpNotFound();
            }
            return View(cor);
        }

        // POST: Cores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cor cor = db.CORES.Find(id);
            db.CORES.Remove(cor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/TiposLinhaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Arthesanatus.Models;
using Arthesanatus.Models.Context;

namespace Arthesanatus.Controllers
{
    public class TiposLinhaController : Controller
    {
        private ArthesContext db = new ArthesContext();

        // GET: TiposLinha
        public ActionResult Index()
        {
            return View(db.TIPOSLINHAS.ToList());
        }

        // GET: TiposLinha/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoLinha tipoLinha = db.TIPOSLINHAS.Find(id);
            if (tipoLinha == null)
            {
                return HttpNotFound();
            }
            return View(tipoLinha);
        }

        // GET: TiposLinha/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TiposLinha/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TipoLinhaID,Nome,Descricao,DadosTecnicos")] TipoLinha tipoLinha)
        {
            if (ModelState.IsValid)
            {
                db.TIPOSLINHAS.Add(tipoLinha);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tipoLinha);
        }

        // GET: TiposLinha/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoLinha tipoLinha = db.TIPOSLINHAS.Find(id);
            if (tipoLinha == null)
            {
                return HttpNotFound();
            }
            return View(tipoLinha);
        }

        // POST: TiposLinha/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TipoLinhaID,Nome,Descricao,DadosTecnicos")] TipoLinha tipoLinha)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipoLinha).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tipoLinha);
        }

        // GET: TiposLinha/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoLinha tipoLinha = db.TIPOSLINHAS.Find(id);
            if (tipoLinha == null)
            {
                return HttpNotFound();
            }
            return View(tipoLinha);
        }

        // POST: TiposLinha/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TipoLinha tipoLinha = db.TIPOSLINHAS.Find(id);
            db.TIPOSLINHAS.Remove(tipoLinha);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_AvisoExclusao.cshtml
<div class="alert alert-danger" role="alert">
    <h3>Confirma a Exclusão deste Registro?</h3>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Amigurumis</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Geana Arthesanatus","Index","Home",new { area = "" },new { @class = "navbar-brand" })
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Cadastros
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink( "Cores das Linhas", "Index", "Cores" )</li>
                            <li>@Html.ActionLink( "Fabricantes", "Index", "Fabricantes" )</li>
                            <li>@Html.ActionLink( "Linhas", "Index", "Linhas" )</li>
                            <li>@Html.ActionLink( "Receitas", "Index", "Receitas" )</li>
                            <li>@Html.ActionLink( "Revistas", "Index", "Revistas" )</li>
                            <li>@Html.ActionLink( "Tipos de Linhas", "Index", "TiposLinha" )</li>

                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Associar
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Linhas x Receitas","Index","LinhasReceitas")</li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Inventário<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Entrada de Linhas","EstEntrada","Estoque")</li>
                            <li>@Html.ActionLink("Estoque de Linhas","EstManutencao","Estoque")</li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Pesquisas
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Receitas","ConReceitas","Consultas")</li>
                            <li>@Html.ActionLink("Revistas","ConReceitas","Revistas")</li>
                        </ul>
                    </li>
                </ul>
            </div>

        </div>
    </div>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <nav class="navbar navbar-default navbar-fixed-bottom">
                <div class="container" style="padding-top:10px;">
                    <p class="pull-right">&copy; @DateTime.Now.Year - Arthes & Geana</p>
                </div>
            </nav>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts",required: false)

</body>

</html>