Models/Revista.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;

namespace Arthesanatus.Models
{
    [Table("Revista")]
    public class Revista
    {
        public Revista()
        {
            Receitas = new List<Receita>();
        }

        [Key]
        public int RevistaID { get; set; }

        [Required]
        [Display(Name = "Número da Edição")]
        [Range(1,9999)]
        public int NumeroEdicao { get; set; }

        [Required]
        [Display(Name = "Ano da Edição")]
        [Range(2017,2025)]
        public int AnoEdicao { get; set; }

        [Required]
        [Display(Name = "Mês da Edição")]
        public Mes MesEdicao { get; set; }

        [Required]
        [MaxLength(150)]
        [Display(Name = "Tema")]
        public string Tema { get; set; }

        [Display(Name = "Foto de Capa")]
        public byte[] Foto { get; set; }

        [NotMapped]
        public HttpPostedFileBase ArquivoFoto { get; set; }

        public virtual List<Receita> Receitas { get; set; }

    }
}

Controllers/RevistasController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Arthesanatus.Models;
using Arthesanatus.Models.Context;
using Arthesanatus.Util;

namespace Arthesanatus.Controllers
{
    public class RevistasController:Controller
    {
        private ArthesContext db = new ArthesContext();


        public ActionResult Index()
        {
            return View(db.REVISTAS.ToList());
        }


        public ActionResult Details(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Revista revista = db.REVISTAS.Find(id);
            if(revista == null)
            {
                return HttpNotFound();
            }
            return View(revista);
        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Revista revista)
        {
            if(ModelState.IsValid)
            {
                if(revista.ArquivoFoto != null)
                {
                    revista.Foto = FilesHelper.UploadPhoto(revista.ArquivoFoto);
                }
                db.REVISTAS.Add(revista);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(revista);
        }


        public ActionResult Edit(int? id)
       {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Revista revista = db.REVISTAS.Find(id);
            if(revista == null)
            {
                return HttpNotFound();
            }
            return View(revista);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RevistaID,NumeroEdicao,AnoEdicao,MesEdicao,Tema,Foto")] Revista revista)
        {
            if(ModelState.IsValid)
            {
                db.Entry(revista).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(revista);
        }


        public ActionResult Delete(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Revista revista = db.REVISTAS.Find(id);
            if(revista == null)
            {
                return HttpNotFound();
            }
            return View(revista);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Revista revista = db.REVISTAS.Find(id);
            db.REVISTAS.Remove(revista);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult RevistasReceitasVM(int codRevista,string temaRevista){
        
             List<Receita> receita = (from rec in db.RECEITAS
                        where rec.RevistaId.Equals(codRevista)
                        select rec).ToList();

            Revista revista = db.REVISTAS.Find(codRevista);

            ViewBag.rev = revista;

            return View(receita);

        }
        protected override void Dispose(bool disposing)
        {
            if(disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Revistas/Create.cshtml
@model Arthesanatus.Models.Revista

@{
    ViewBag.Title = "Cadastro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cadastro</h2>


@using(Html.BeginForm("Create","Revistas",FormMethod.Post,new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Revista</h4>
        <hr />
        @Html.ValidationSummary(true,"",new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Tema,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tema,new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tema,"",new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroEdicao,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroEdicao,new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroEdicao,"",new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MesEdicao,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.MesEdicao,htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MesEdicao,"",new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnoEdicao,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnoEdicao,new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnoEdicao,"",new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.ArquivoFoto,new { type = "file" })
                </span>
                @Html.ValidationMessageFor(model => model.ArquivoFoto,"",new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retornar à Listagem","Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Revistas/Delete.cshtml
@model Arthesanatus.Models.Revista

@{
    ViewBag.Title = "Excluir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Excluir</h2>

@Html.Partial("~/Views/Shared/_AvisoExclusao.cshtml")

<div>
    <h4>Revista</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Tema)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tema)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumeroEdicao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroEdicao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MesEdicao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MesEdicao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnoEdicao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnoEdicao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Foto)
        </dd>

    </dl>

    @using(Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-danger" /> 
            @Html.ActionLink("Retornar à Listagem","Index")
        </div>
    }
</div>

Views/Revistas/Details.cshtml
@model Arthesanatus.Models.Revista

@{
    ViewBag.Title = "Detalhes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalhes</h2>

<div>
    <h4>Revista</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NumeroEdicao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroEdicao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnoEdicao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnoEdicao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MesEdicao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MesEdicao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tema)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tema)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Foto)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.RevistaID }) |
    @Html.ActionLink("Retornar à Listagem", "Index")
</p>

Views/Revistas/Edit.cshtml
@model Arthesanatus.Models.Revista

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Revista</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RevistaID)

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroEdicao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroEdicao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroEdicao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnoEdicao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnoEdicao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnoEdicao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MesEdicao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.MesEdicao, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MesEdicao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tema, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tema, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tema, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Foto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retornar à Listagem", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Revistas/Index.cshtml
@model IEnumerable<Arthesanatus.Models.Revista>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Listagem - Revista</h2>

<p>
    @Html.ActionLink("Novo Registro","Create")
</p>
<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NumeroEdicao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AnoEdicao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MesEdicao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tema)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Foto)
        </th>
        <th></th>
    </tr>

    @foreach(var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroEdicao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AnoEdicao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MesEdicao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tema)
            </td>
            <td>
                <img src="~/Content/img/index-bolsa.jpg" alt="Image" style="width:100px;height:150px;max-width: 100%; height: auto;" />
            </td>
            <td style="text-align:right">
                @Html.ActionLink("Ver as Receitas","RevistasReceitasVM",new { codRevista = item.RevistaID,temaRevista = item.Tema }) |
                @Html.ActionLink("Editar","Edit",new { id = item.RevistaID }) |
                @Html.ActionLink("Details","Details",new { id = item.RevistaID }) |
                @Html.ActionLink("Delete","Delete",new { id = item.RevistaID })
            </td>
        </tr>
    }

</table>

Views/Revistas/RevistasReceitasVM.cshtml
@model IEnumerable<Arthesanatus.Models.Receita>

@{
    ViewBag.Title = "Receitas - Revista";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="alert alert-info" role="alert">
    <h2>Tema: @ViewBag.rev.Tema</h2>
    <p>
        <div style="padding-left: 40px;">
            <i><strong>Edição Número: @ViewBag.rev.NumeroEdicao</strong></i>
        </div>
        <div style="padding-left: 40px; font-size:smaller;">
            <i>@ViewBag.rev.MesEdicao - @ViewBag.rev.AnoEdicao</i>
        </div>

    </p>
</div>
<br />
<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>

    </tr>

    @foreach(var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
        </tr>
    }

</table>
<br />

<div>
    @Html.ActionLink("Retornar à Listagem","Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}